# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('B', 'Back-end'), ('F', 'Front-end')], default='B', max_length=1)),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/skills')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img_desktop', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/works')),
                ('img_mobile', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/works')),
                ('order', models.PositiveIntegerField(default=0)),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.Skill')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='WorkAddition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('img', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='img/works')),
                ('order', models.PositiveIntegerField(default=0)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Work')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
