# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20161127_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workdetail',
            name='work',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='img_desktop',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='work',
            name='img_mobile',
        ),
        migrations.AddField(
            model_name='work',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='WorkDetail',
        ),
    ]
