# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20161128_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='img',
        ),
        migrations.RemoveField(
            model_name='work',
            name='description',
        ),
    ]
