# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_aboutme_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name_plural': 'About me'},
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='img/logo'),
        ),
    ]
